FROM golang:1

MAINTAINER zerro "zerrozhao@gmail.com"

ENV GOPROXY https://goproxy.io

WORKDIR /src/jarvissh

COPY ./go.* /src/jarvissh/

RUN go mod download

COPY . /src/jarvissh

RUN go test ./... -cover